language: node_js
sudo: required
node_js:
- "5"
script:
- npm run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy; fi
cache:
  directories:
  - node_modules
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: nobody@nobody.org
  - GITHUB_REPO: MiniaspReading/JavaScript-The_Good_Parts
  - GIT_SOURCE: _docpress
